### ISSUE TITLE
Cannot npm install from project root

### ISSUE THREAD

**Issue by rainabba** [hapijs/tv#116]
I've cloned the project to poke around regarding the SSL issue (which looks like it may be far easier than I initially expected), but I cannot npm install. See error below:

Since it seems that Windows isn't given as compatible (even though it's supposed to be a first-class citizen in the Node ecosystem; a fact that continues to haunt me), I will clarify that I'm running Windows 8.1 Pro. Also, node 12.7, Hapi 9.1, npm 2.13.

```
myproject\lib\plugins\tv [master]> npm install

> tv@4.1.1 prepublish myproject\lib\plugins\tv
> npm run build


> tv@4.1.1 build myproject\lib\plugins\tv
> npm run build-js && npm run build-styles && npm run build-test && npm run copy-fonts && npm run copy-assets


> tv@4.1.1 build-js myproject\lib\plugins\tv
> browserify -t hbsfy -e source/js/app.js source/js/**/*.js > public/js/main.js -d

Error: Cannot find module 'myproject\lib\plugins\tv\source\js\**\*.js' from 'myproject\lib\plugins\tv'
    at myproject\lib\plugins\tv\node_modules\browserify\node_modules\resolve\lib\async.js:55:21
    at load (myproject\lib\plugins\tv\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (myproject\lib\plugins\tv\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at myproject\lib\plugins\tv\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-js"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! tv@4.1.1 build-js: `browserify -t hbsfy -e source/js/app.js source/js/**/*.js > public/js/main.js -d`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tv@4.1.1 build-js script 'browserify -t hbsfy -e source/js/app.js source/js/**/*.js > public/js/main.js -d'.
npm ERR! This is most likely a problem with the tv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -t hbsfy -e source/js/app.js source/js/**/*.js > public/js/main.js -d
npm ERR! You can get their info via:
npm ERR!     npm owner ls tv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     myproject\lib\plugins\tv\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! tv@4.1.1 build: `npm run build-js && npm run build-styles && npm run build-test && npm run copy-fonts && npm run copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tv@4.1.1 build script 'npm run build-js && npm run build-styles && npm run build-test && npm run copy-fonts && npm run copy-assets'.
npm ERR! This is most likely a problem with the tv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-js && npm run build-styles && npm run build-test && npm run copy-fonts && npm run copy-assets
npm ERR! You can get their info via:
npm ERR!     npm owner ls tv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     myproject\lib\plugins\tv\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! tv@4.1.1 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tv@4.1.1 prepublish script 'npm run build'.
npm ERR! This is most likely a problem with the tv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls tv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     myproject\lib\plugins\tv\npm-debug.log
myproject\lib\plugins\tv [master]>
```

**Comment by rainabba** [comment]
Project seems to work despite the error.
