### ISSUE TITLE
Cannot read property 'statusCode' of null

### ISSUE THREAD

**Issue by TangMonk** [hapijs/tv#136]
Somethings the sever will throw error:

```
/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.6.1.0@tv/lib/index.js:182
                    statusCode: request.response.statusCode,
                                                ^

TypeError: Cannot read property 'statusCode' of null
    at server.on (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.6.1.0@tv/lib/index.js:182:49)
    at invoke (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.1.2.5@podium/lib/index.js:239:30)
    at each (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.1.2.5@podium/lib/index.js:243:13)
    at Object.exports.parallel (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.2.1.1@items/lib/index.js:70:13)
    at Object.internals.emit (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.1.2.5@podium/lib/index.js:260:18)
    at module.exports.internals.Plugin.internals.Podium._emit (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.1.2.5@podium/lib/index.js:140:15)
    at each (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.1.2.5@podium/lib/index.js:181:47)
    at Object.exports.parallel (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.2.1.1@items/lib/index.js:70:13)
    at relay (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.1.2.5@podium/lib/index.js:182:15)
    at Object.internals.emit (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.1.2.5@podium/lib/index.js:186:16)
    at internals.emitEmitter (/Users/tangmonk/Documents/mygit/nodejs/my_project/admin/api/node_modules/.1.2.5@podium/lib/index.js:272:15)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by Marsup** [comment]
Any way to reproduce that ?

**Comment by TangMonk** [comment]
@Marsup it is hard to reproduce, It is uncertainty
